// Generated by CoffeeScript 1.6.3
this.Emitter = (function() {
  Emitter.prototype.rate = 300;

  Emitter.prototype.max = 50;

  Emitter.prototype.onemit = function() {};

  function Emitter(o) {
    _.extend(this, o);
    _.bindAll(this, 'update', 'emit');
    this.count = 0;
    setInterval(this.update, this.rate);
  }

  Emitter.prototype.emit = function() {
    if (this.count++ < this.max) {
      this.lastemit = Date.now();
      return typeof this.generator === "function" ? this.generator() : void 0;
    }
  };

  Emitter.prototype.update = function() {
    if ((this.lastemit == null) || (Date.now() - this.lastemit) > this.rate) {
      return this.emit();
    }
  };

  return Emitter;

})();
