// Generated by CoffeeScript 1.6.3
var _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

this.Food = (function(_super) {
  __extends(Food, _super);

  function Food() {
    _ref = Food.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Food.prototype.size = 40;

  Food.prototype.setSize = function(s) {
    if (!s) {
      this.world.remqueue.push(this.id);
      return 0;
    } else if (s !== this.size) {
      this.size = s;
      this.root.remove(this.objects.body);
      this.root.add(this.objects.body = this.generators().body());
      return this.size;
    }
  };

  Food.prototype.generators = function() {
    return {
      body: function() {
        var box, geo, mat;
        geo = new THREE.CubeGeometry(this.size, this.size / 2, this.size);
        mat = new THREE.MeshPhongMaterial({
          ambient: 0x111111,
          color: 0xbbbbee,
          specular: 0x009900,
          shininess: 30,
          shading: THREE.FlatShading
        });
        box = new THREE.Mesh(geo, mat);
        box.position.set(0, this.size / 4, 0);
        return box;
      }
    };
  };

  return Food;

})(Visual);
