// Generated by CoffeeScript 1.6.3
var _this = this;

Meteor.startup(function() {
  var time, updates;
  if (_this.viewport == null) {
    _this.viewport = new Visualizr({
      container: $('body'),
      visuals: function() {
        return {
          world: function() {
            return new World({
              food: 50,
              size: 3000
            });
          }
        };
      }
    });
  }
  updates = null;
  time = 0;
  return updates != null ? updates : updates = window.setInterval(function() {
    var err;
    try {
      return _this.viewport.update(time++);
    } catch (_error) {
      err = _error;
      debugger;
      throw err;
    }
  }, 70);
});
