// Generated by CoffeeScript 1.6.3
var _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

this.Nest = (function(_super) {
  __extends(Nest, _super);

  function Nest() {
    _ref = Nest.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Nest.prototype.size = 80;

  Nest.prototype.ants = 30;

  Nest.prototype.food = 0;

  Nest.prototype.initialize = function() {
    var _this = this;
    return this.antEmitter = new Emitter({
      rate: 3000,
      max: this.ants,
      generator: function() {
        var id;
        id = "ant:" + (_this.newid());
        return _this.world.addqueue.push([
          id, new Ant({
            id: id,
            x: 0,
            y: 0,
            z: 0,
            world: _this.world
          })
        ]);
      }
    });
  };

  Nest.prototype.update = function(t) {
    return Nest.__super__.update.call(this, t);
  };

  Nest.prototype.generators = function() {
    return {
      entrance: function() {
        var geo, mat, mesh;
        geo = new THREE.SphereGeometry(this.size, 10, 10, 0, 2 * Math.PI, 0.2 * Math.PI, 0.5 * Math.PI);
        mat = new THREE.MeshNormalMaterial();
        mesh = new THREE.Mesh(geo, mat);
        mesh.scale.set(1, 0.5, 1);
        return mesh;
      }
    };
  };

  return Nest;

})(Visual);
